version: '3'
services:
  web:
    build:
      context: ./bin/webserver
    ports:
      - '80:80'
    volumes:
      - './www:/www'
      - './config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - code-network
  php:
    build:
      context: ./bin/php
    volumes:
      - './www:/www'
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
